[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "torchcor"
version = "0.1.2"
description = "Efficient EP simulations on GPUs"
authors = [{ name = "Bei Zhou", email = "bei.zhou@imperial.ac.uk" }]
dependencies = []

[tool.setuptools]
packages = ["torchcor", "torchcor.core", "torchcor.ionic", "torchcor.simulator"]  # Explicitly list packages